%project image deblurring
clear;
clc;
A=imread('C:\Users\LEGION\OneDrive - 联合学术\report\Tex2\picture\1.jpg');
B=imread('C:\Users\LEGION\OneDrive - 联合学术\report\Tex2\picture\2.jpg');
C=imread('C:\Users\LEGION\OneDrive - 联合学术\report\Tex2\picture\3.jpg');
[m1,n1,k1]=size(A);
[m2,n2,k2]=size(B);
[m3,n3,k3]=size(C);
%LA1=zeros(m1,n1,3);
%SA1=LA1;LA2=LA1;LA3=LA1;SA2=LA1;SA3=LA1;
%LA1=zeros(m2,n2,3);
%SA1=LA1;LA2=LA1;LA3=LA1;SA2=LA1;SA3=LA1;
%LA1=zeros(m3,n3,3);
%SA1=LA1;LA2=LA1;LA3=LA1;SA2=LA1;SA3=LA1;
for i=1:3
    [LA1(:,:,i),SA1(:,:,i)]=IT(double(A(:,:,i)),200);
    [LA2(:,:,i),SA2(:,:,i)]=APG(double(A(:,:,i)),200);
    [LA3(:,:,i),SA3(:,:,i)]=IALM(double(A(:,:,i)),200);
    [LB1(:,:,i),SB1(:,:,i)]=IT(double(B(:,:,i)),200);
    [LB2(:,:,i),SB2(:,:,i)]=APG(double(B(:,:,i)),200);
    [LB3(:,:,i),SB3(:,:,i)]=IALM(double(B(:,:,i)),200);
    [LC1(:,:,i),SC1(:,:,i)]=IT(double(C(:,:,i)),200);
    [LC2(:,:,i),SC2(:,:,i)]=APG(double(C(:,:,i)),200);
    [LC3(:,:,i),SC3(:,:,i)]=IALM(double(C(:,:,i)),200);
end
SA1=abs(SA1);
SA1(SA1>20)=255;
SA2=abs(SA2);
SA2(SA2>20)=255;
SA3=abs(SA3);
SA3(SA3>20)=255;
subplot(3,3,1);
imshow(A);
title('Original picture');
subplot(3,3,2);
imshow(uint8(LA1));
title('IT-Low-rank picture');
subplot(3,3,3);
imshow(uint8(SA1));
title('IT-noise picture');
subplot(3,3,4);
imshow(A);
title('Original picture');
subplot(3,3,5);
imshow(uint8(LA2));
title('APG-Low-rank picture');
subplot(3,3,6);
imshow(uint8(SA2));
title('APG-noise picture');
subplot(3,3,7);
imshow(A);
title('Original picture');
subplot(3,3,8);
imshow(uint8(LA3));
title('IALM-Low-rank picture');
subplot(3,3,9);
imshow(uint8(SA3));
title('IALM-noise picture');

