SC1=abs(SC1);
SC1(SC1>20)=255;
SC2=abs(SC2);
SC2(SC2>20)=255;
SC3=abs(SC3);
SC3(SC3>20)=255;
subplot(3,3,1);
imshow(C);
title('Original picture');
subplot(3,3,2);
imshow(uint8(LC1));
title('IT-Low-rank picture');
subplot(3,3,3);
imshow(uint8(SC1));
title('IT-noise picture');
subplot(3,3,4);
imshow(C);
title('Original picture');
subplot(3,3,5);
imshow(uint8(LC2));
title('APG-Low-rank picture');
subplot(3,3,6);
imshow(uint8(SC2));
title('APG-noise picture');
subplot(3,3,7);
imshow(C);
title('Original picture');
subplot(3,3,8);
imshow(uint8(LC3));
title('IALM-Low-rank picture');
subplot(3,3,9);
imshow(uint8(SC3));
title('IALM-noise picture');